apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyst-ohlcv
  namespace: bigdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analyst-ohlcv
  template:
    metadata:
      labels:
        app: analyst-ohlcv
    spec:
      containers:
        - name: analyst-ohlcv
          image: analyst_ohlcv:latest
          # Spark sẽ dùng spark-submit, không cần CMD override
          envFrom:
            - configMapRef:
                name: bigdata-config
            - secretRef:
                name: airflow-secret
          resources:
            limits:
              memory: "500Mi"
              cpu: "0.5"
