apiVersion: apps/v1
kind: Deployment
metadata:
  name: daily-ohlcv
  namespace: bigdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daily-ohlcv
  template:
    metadata:
      labels:
        app: daily-ohlcv
    spec:
      containers:
        - name: daily-ohlcv
          image: daily_ohlcv:latest
          envFrom:
            - configMapRef:
                name: bigdata-config
            - secretRef:
                name: airflow-secret
          resources:
            limits:
              memory: "500Mi"
              cpu: "0.5"
