apiVersion: apps/v1
kind: Deployment
metadata:
  name: datanode
  namespace: bigdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datanode
  template:
    metadata:
      labels:
        app: datanode
    spec:
      containers:
        - name: datanode
          image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
          env:
            - name: CLUSTER_NAME
              value: "lambda-cluster"
            - name: CORE_CONF_fs_defaultFS
              value: "hdfs://namenode:8020"
          ports:
            - containerPort: 50075
          volumeMounts:
            - name: datanode-data
              mountPath: /hadoop/dfs/data
      volumes:
        - name: datanode-data
          hostPath:
            path: ./volumes/hdfs/datanode
