apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: bigdata
data:
  KAFKA_BROKER_ID: "1"
  KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
